### ISSUE TITLE
🛠️ Repo: pnpm run lint inside node:20 container reports 6721 problems

### ISSUE THREAD

**Issue by pjonsson** [JoshuaKGoldberg/TypeStat#2028] opened 2024-11-30 17:41 UTC
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/TypeStat/issues?q=is%3Aissue) and found none that matched my issue.

### Expected

Same result as lint job in CI (which runs `pnpm lint` rather than the `pnpm run lint` documented in DEVELOPMENT.md).

### Actual

Reproducer (running as root inside the container so pnpm can be installed easily):
```
git clone https://github.com/JoshuaKGoldberg/TypeStat
cd TypeStat
docker run --user root --rm -it -v `pwd`:/files node:20 bash
```
Then inside the container, run:
```
$ cd files
$ npm install -g pnpm
$ pnpm install
$ pnpm run lint
<many lines>
/files/bin/typestat.mjs
  3:1  warning  Unused eslint-disable directive (no problems were reported from 'n/no-missing-import')

✖ 6721 problems (6720 errors, 1 warning)
  6720 errors and 1 warning potentially fixable with the `--fix` option.

 ELIFECYCLE  Command failed with exit code 1.
```

### Additional Info

I have never used pnpm before, but I do almost all my development inside containers and it has worked well for other projects with other package managers (yarn, poetry, uv, npm).

**Comment by pjonsson** [comment] 2024-11-30 17:52
I even spent time on searching to figure out if I was doing something obviously stupid, but without success. Scrolling up a bit reveals that (most of) the errors are from files under `.pnpm-store` (whatever that is):
```
/files/.pnpm-store/v3/files/ff/edc644bedd0c01847cce93b1e424fd4fa68b5f1353632cf48dd494b754321cf685bbc635329d8fdc678b05df52a818847c51c74fbc5272a4be5370554f9c59-index.json
  1:43   error  Expected object keys to be in ascending order. 'requiresBuild' should be before 'version'      jsonc/sort-keys
  1:65   error  Expected object keys to be in ascending order. 'files' should be before 'requiresBuild'        jsonc/sort-keys
  1:422  error  Expected object keys to be in ascending order. 'package.json' should be before 'src/index.js'  jsonc/sort-keys
  1:598  error  Expected object keys to be in ascending order. 'README.md' should be before 'package.json'     jsonc/sort-keys
```
Even if I delete that directory and run `pnpm lint`, I still get the last line warning about unused eslint-disable directive on bin/typestat.mjs, which is apparently not a problem for the CI.

**Comment by JoshuaKGoldberg** [comment] 2024-12-01 21:02
> `pnpm lint` rather than the `pnpm run lint`

The two are equivalent. The `run` is implied. You do need `run` when adding extra flags in some cases. https://pnpm.io/cli/run

> Docker

I can understand why you'd use Docker, but I don't use it myself. All my repos (i.e. those set up with https://github.com/JoshuaKGoldberg/create-typescript-app) require only Node.js and pnpm to run. So anything that works differently on Docker images is a _"you're on your own"_ setup.

In this case, the problem is:

> `.pnpm-store/`

That's not normally placed in repos when working with pnpm outside of containers. By default it's placed outside the repo, in some shared directory. That way multiple repos can reuse their pnpm installs. 

By using a single Docker container, I _believe_ you're forcing pnpm to create a store per repository. Which, if I'm right, means every repository will have to have its own store. No more package duplication! 😬 

A few relevant docs:

* https://pnpm.io/motivation
* https://pnpm.io/cli/store
* https://pnpm.io/faq#why-does-my-node_modules-folder-use-disk-space-if-packages-are-stored-in-a-global-store

> I still get the last line warning about unused eslint-disable directive on bin/typestat.mjs, which is apparently not a problem for the CI.

Oh, ha, that's a good find and a separate issue. ESLint _warnings_ don't fail the build; ESLint _errors_ do. And this is apparently set to _warn_. Filed #2034.

Anyway, closing this out - but thanks for filing! I'd been meaning to fix #2034 for a few days but kept getting distracted. 🙂

**Closed by JoshuaKGoldberg** 2024-12-01 21:02 UTC
Labels: area: tooling

**Comment by pjonsson** [comment] 2024-12-01 21:46
> By using a single Docker container, I _believe_ you're forcing pnpm to create a store per repository. Which, if I'm right, means every repository will have to have its own store. No more package duplication! 😬

Well, now that we know what it is: the repository already has `node_modules` and `pnpm-lock.yaml` in `ignorePatterns`, are you against adding `.pnpm-store` in `ignorePatterns`?

**Comment by JoshuaKGoldberg** [comment] 2024-12-02 14:43
I am. I used to be a lot more open to additional _"useful for some"_ `.gitignore` properties: `.pnpm-store`, `pnpm-debug.log`, etc. The list is unbounded. Folks steadily request more and more be added until the file is huge and confusing.
