### ISSUE TITLE
incorrectly adding arrow

### ISSUE THREAD

**Issue by devinrhode2** [JoshuaKGoldberg/TypeStat#1045] opened 2022-08-04 18:30 UTC
Before typestat:
```tsx
import * as Yup from "yup";
import isEqual from "lodash/isEqual";
import { DEFAULT_MAX_MESSAGE_LENGTH } from "constants/defaults";

// eslint-disable-next-line func-names
Yup.addMethod(Yup.object, "uniqueProperty", function (propertyName, message) {
  // eslint-disable-next-line func-names
  return this.test("unique", message, function (value) {
    if (!value || !value[propertyName]) {
      return true;
    }

    if (
      this.parent
        .filter((v) => {
          return v !== value;
        })
        .some((v) => {
          return isEqual(v[propertyName], value[propertyName]);
        })
    ) {
      throw this.createError({
        path: `${this.path}.${propertyName}`,
      });
    }

    return true;
  });
});
```
after:
```tsx
import * as Yup from "yup";
import isEqual from "lodash/isEqual";
import { DEFAULT_MAX_MESSAGE_LENGTH } from "constants/defaults";

// eslint-disable-next-line func-names
Yup.addMethod(Yup.object, "uniqueProperty", function (propertyName: string | number, message) {
  // eslint-disable-next-line func-names
  return this.test("unique", message, function (value: { [x: string]: any; }) => {
    if (!value || !value[propertyName]) {
      return true;
    }

    if (
      this.parent
        .filter((v: { [x: string]: any; }) => {
          return v !== value;
        })
        .some((v: { [x: string]: any; }) => {
          return isEqual(v[propertyName], value[propertyName]);
        })
    ) {
      throw this.createError({
        path: `${this.path}.${propertyName}`,
      });
    }

    return true;
  });
});
```

Line 8 incorrectly gets an arrow added `=>`

### 🐛 Bug Report

-   TypeStat version: X.X.X
-   TypeScript version: X.X.X
-   Node version: X.X.X

**Comment by JoshuaKGoldberg** [comment] 2022-08-05 18:12
Hey @devinrhode2, thanks for using TypeStat and posting this issue!

But, I can't reproduce this locally. Could you please provide a reproduction that I can use to reproduce these changes? If this is private source code I'm happy to sign an NDA & be sent it directly via the email on my GitHub profile.

**Comment by JoshuaKGoldberg** [comment] 2022-10-10 04:50
I'm going to go ahead and close this as not reproducing, since it's been 2 months without a repo. Please do post back -@devinrhode2 or anybody else- if you can demonstrate this bug happening, and I'll gladly take a look!

**Closed by JoshuaKGoldberg** 2022-10-10 04:50 UTC
Labels: type: bug, status: needs reproduction
